# Generated by Django 5.2.10 on 2026-08-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('desc', models.TextField(max_length=100, verbose_name='Description')),
                ('button', models.CharField(max_length=20, verbose_name='Button')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
