# Generated by Django 5.2.10 on 2026-08-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms',
            name='button',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Button'),
        ),
    ]
