# Generated by Django 5.2.10 on 2026-08-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeleBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('chat_id', models.CharField(max_length=255)),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'TeleBot Setting',
                'verbose_name_plural': 'TeleBot Settings',
            },
        ),
    ]
