# Generated by Django 5.2.10 on 2026-08-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_cms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('desc', models.TextField(max_length=100, verbose_name='Description')),
                ('image', models.ImageField(upload_to='service_images/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
