# Generated by Django 5.2.10 on 2026-08-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_desc',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Order Description'),
        ),
    ]
