# Generated by Django 5.2.10 on 2026-08-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_order_order_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
