# Generated by Django 5.2.10 on 2026-08-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_order_order_status_delete_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='desc',
            field=models.TextField(max_length=200, verbose_name='Description'),
        ),
    ]
