# Generated by Django 5.2.10 on 2026-08-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_service_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms',
            name='image',
            field=models.ImageField(max_length=200, upload_to='images/', verbose_name='Image'),
        ),
    ]
